### PR TITLE
Fix for resolutions that differs from 1920x1080

### PR DESCRIPTION
**Pull request by TideSofDarK**
Strange problem with resolutions. Even on 1360x768 you need to use 1920x1080 positions.
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama/Layout
Check latest paragraph.

### CODE REVIEW

**Comment by musshorn** [comment]
Good find, but I'm not sure that patch actually fixes the issue. The problem is related to line 24, where i do a seemlying random subtraction by 25. That 25 will need to change with the resolution I think. Multiplying it by the screen ratio will probably work fine (so if it's 25 at 16:9 then solve for other resolutions)

**Comment by TideSofDarK** [comment]
Yeah. I forgot to test 4:3. Let's go with your solution.

**Comment by musshorn** [comment]
Fixed this in todays update. Thanks for the earlier work though.

**Comment by TideSofDarK** [comment]
Glad i could help!

**Pull request closed without merging**
